name: API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore UrlShortener.sln
    - name: Build
      run: dotnet build UrlShortener.sln --no-restore
    - name: Test
      run: dotnet test UrlShortener.sln --no-build --verbosity normal